In [24]:
import tensorflow as tf
print(tf.__version__)
tf.config.list_physical_devices()

2.9.0


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [25]:
#Tensor - n-dimensional array of numbers

#Creating a tensor (0 dimension - single number):
tensor1 = tf.constant(7)
tensor1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [26]:
#Creating a vector (1 dimension - number with direction):
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [27]:
#Creating a matrix (more than 1 dimension):
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [29]:
#Creating a matrix with specified dtype:
a_matrix = tf.constant([[10.,7.], [7.,10.], [8.,9.]], dtype = tf.float16)
a_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [31]:
#Creating a matrix with specified dtype:
a_matrix = tf.constant([[[10.,7.], [7.,10.], [8.,9.]], [[10.,7.], [7.,10.], [8.,9.]]], dtype = tf.float16)
a_matrix

<tf.Tensor: shape=(2, 3, 2), dtype=float16, numpy=
array([[[10.,  7.],
        [ 7., 10.],
        [ 8.,  9.]],

       [[10.,  7.],
        [ 7., 10.],
        [ 8.,  9.]]], dtype=float16)>

In [33]:
#Create variable tensors -- can change the values inside the tensor:
tensor1V = tf.Variable([12,12])
tensor1V[1].assign(6)
tensor1V

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  6], dtype=int32)>

In [38]:
#Creating random tensors:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [39]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [46]:
#Shuffle a tensor (ie. Instead of training with 1000 ramen pics and then 100 hotdog pics in order
#, should mix them up so that the model isnt as biased/more accurate)
random_1

tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [51]:
#Convert numpy array into tensor (tensor can run on GPU):
import numpy as np
#Create numpy array
numpy_A = np.arange(1,25, dtype =np.int32)

print(numpy_A)

#Convert to tensor, and change the shape
A = tf.constant(numpy_A, shape = (2,3,4))
print(A)

B = tf.constant(numpy_A, shape = (6,4))
print(B)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]], shape=(6, 4), dtype=int32)


In [52]:
#Tensor Key attributes:

print("Datatype of every element:", A.dtype)
print("No. of dims (rank):", A.ndim)
print("Shape of tensor:", A.shape)
print("Elements along 0 axis:", A.shape[0])
print("Elements along last axis:", A.shape[-1])
print("Total elements in tensor:", tf.size(A))
print("Total elements in tensor:", tf.size(A).numpy())

Datatype of every element: <dtype: 'int32'>
No. of dims (rank): 3
Shape of tensor: (2, 3, 4)
Elements along 0 axis: 2
Elements along last axis: 4
Total elements in tensor: tf.Tensor(24, shape=(), dtype=int32)
Total elements in tensor: 24


In [59]:
#Indexing the tensor:

A[:2,:2,:4]

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20]]], dtype=int32)>

In [68]:
#Expanding on tensor:
print(A)
new_A = A[:,tf.newaxis, :, :]
print(new_A)

#ALternative to tf.newaxis:
tf.expand_dims(new_A, axis = -1) # -1 means expand final axis
print(new_A)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(2, 1, 3, 4), dtype=int32)
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(2, 1, 3, 4), dtype=int32)


# Matrix Multiplication

In [70]:
#Dot Product

C = tf.constant(numpy_A, shape = (2,3,4))
print(C)

D = tf.constant(numpy_A, shape = (4,6))
print(D)

tf.matmul(C,D)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]], shape=(4, 6), dtype=int32)


<tf.Tensor: shape=(2, 3, 6), dtype=int32, numpy=
array([[[ 130,  140,  150,  160,  170,  180],
        [ 290,  316,  342,  368,  394,  420],
        [ 450,  492,  534,  576,  618,  660]],

       [[ 610,  668,  726,  784,  842,  900],
        [ 770,  844,  918,  992, 1066, 1140],
        [ 930, 1020, 1110, 1200, 1290, 1380]]], dtype=int32)>

In [87]:
#Note, can use transpose also, but the values are flipped
print(tf.transpose(D))

#Can use tf.reshape to change the shape of a tensor:
D = tf.reshape(D,shape=(1,4,6))

print(D)
tf.matmul(C,D)

tf.Tensor(
[[[ 1]
  [ 7]
  [13]
  [19]]

 [[ 2]
  [ 8]
  [14]
  [20]]

 [[ 3]
  [ 9]
  [15]
  [21]]

 [[ 4]
  [10]
  [16]
  [22]]

 [[ 5]
  [11]
  [17]
  [23]]

 [[ 6]
  [12]
  [18]
  [24]]], shape=(6, 4, 1), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]], shape=(1, 4, 6), dtype=int32)


<tf.Tensor: shape=(2, 3, 6), dtype=int32, numpy=
array([[[ 130,  140,  150,  160,  170,  180],
        [ 290,  316,  342,  368,  394,  420],
        [ 450,  492,  534,  576,  618,  660]],

       [[ 610,  668,  726,  784,  842,  900],
        [ 770,  844,  918,  992, 1066, 1140],
        [ 930, 1020, 1110, 1200, 1290, 1380]]], dtype=int32)>

In [89]:
#Changing datatype of tensor:
D = tf.cast(D, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(1, 4, 6), dtype=float16, numpy=
 array([[[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.],
         [13., 14., 15., 16., 17., 18.],
         [19., 20., 21., 22., 23., 24.]]], dtype=float16)>,
 tf.float16)

In [105]:
#Aggregating of tensors:

E = tf.constant(np.random.randint(0,200,size = 100))
E

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([112,  33, 163, 140, 197,  55, 111, 157,  10, 146, 112, 109, 132,
        90, 155,  83,  64, 129,  25, 114, 107, 191,  68,  73,  92,  97,
        42,  37,  46, 122,  75,  80,  88, 175,  73,  98,  46,  73,  57,
        12, 184,  16,  10, 160,  43, 173, 163,  26, 135, 172, 170,  15,
       188, 101,  31, 160,  55,  36,  95, 187,   3, 190, 127, 144, 196,
       184, 120,  45,   9, 113,  95,   4,  82,   9, 178, 114,  97, 175,
        77,   7,  25, 116,  81,  36, 187,   1,  74,  37,  69, 181, 112,
        92,   1, 102, 134, 187, 108,  88,  57, 145])>

In [116]:
#Find Minimum:
print("Sum:", tf.reduce_min(E).numpy())

#Find Max:
print("Max:", tf.reduce_max(E).numpy())

#Find mean:
print("Mean:",tf.reduce_mean(E).numpy())

#Find sum:
print("Sum:",tf.reduce_sum(E).numpy())

#Find Variance (theres a few diff ways to do it):
import tensorflow_probability as tfp
print("Variance:", tfp.stats.variance(E).numpy())

#Positional Maximum:
print("Positional max index:", tf.argmax(E).numpy())
print("Positional max value:", E[tf.argmax(E)].numpy())

#Positional Minimum:
print("Positional min index:", tf.argmin(E).numpy())
print("Positional min value:", E[tf.argmin(E)].numpy())

#Squeezing a tensor -- removing all 1 dimensions from tensor:
numpy_0 = np.arange(1,25, dtype =np.int32)
tensor0 = tf.constant(numpy_0, shape=(1,1,1,1,1,2,3,4))
print(tf.squeeze(tensor0))

#One-hot encoding tensors
#List of indices
A_list = [1,2]

tf.one_hot(A_list, depth=2)

Sum: 1
Max: 197
Mean: 97
Sum: 9711
Variance: 3308
Positional max index: 4
Positional max value: 197
Positional min index: 85
Positional min value: 1
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 1.],
       [0., 0.]], dtype=float32)>

In [118]:
tf.config.list_physical_devices('GPU')

[]